apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: "enmasseproject/kafka-statefulsets:latest"
          securityContext:
            runAsUser: 0
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          command:
            - /opt/kafka/kafka_run.sh
          volumeMounts:
            - name: kafka-storage
              mountPath: /tmp/kafka/
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
